#!/usr/bin/env bash

# Copyright (c) 2021-2026 community-scripts ORG
# Author: ggfevans
# License: MIT | https://github.com/community-scripts/ProxmoxVED/raw/main/LICENSE
# Source: https://github.com/RackulaLives/Rackula

source /dev/stdin <<<"$FUNCTIONS_FILE_PATH"
color
verb_ip6
catch_errors
setting_up_container
network_check
update_os

msg_info "Installing Dependencies"
$STD apt install -y \
  nginx \
  unzip \
  ca-certificates
msg_ok "Installed Dependencies"

msg_info "Creating rackula user"
if ! id -u rackula >/dev/null 2>&1; then
  useradd --system --user-group --home-dir /opt/rackula --shell /usr/sbin/nologin rackula
fi
msg_ok "Created rackula user"

msg_info "Installing Bun"

export BUN_INSTALL="/usr/local/bun"

BUN_INSTALLER=$(mktemp)
curl_with_retry "https://bun.sh/install" "$BUN_INSTALLER"
$STD bash "$BUN_INSTALLER"
rm -f "$BUN_INSTALLER"
if [ ! -x /usr/local/bun/bin/bun ]; then
  msg_error "Bun installation failed: /usr/local/bun/bin/bun not found or not executable"
  exit 1
fi
ln -sf /usr/local/bun/bin/bun /usr/local/bin/bun
ln -sf /usr/local/bun/bin/bunx /usr/local/bin/bunx
msg_ok "Installed Bun"

fetch_and_deploy_gh_release "rackula" "RackulaLives/Rackula" "prebuild" "latest" "/opt/rackula" "rackula-lxc-*.tar.gz"

msg_info "Installing Rackula"
mkdir -p /opt/rackula/data
mkdir -p /etc/nginx/snippets

SECURITY_HEADERS_SRC="/opt/rackula/config/security-headers.conf"
if [ ! -f "$SECURITY_HEADERS_SRC" ]; then
  msg_error "Required config file missing: $SECURITY_HEADERS_SRC (release may be incomplete)"
  exit 1
fi
cp "$SECURITY_HEADERS_SRC" /etc/nginx/snippets/security-headers.conf

chown -R root:root /opt/rackula/frontend
find /opt/rackula/frontend -type d -exec chmod 755 {} \;
find /opt/rackula/frontend -type f -exec chmod 644 {} \;
chown -R rackula:rackula /opt/rackula/{api,data}
chmod 750 /opt/rackula/data
msg_ok "Installed Rackula"

msg_info "Generating API write token"
API_WRITE_TOKEN=$(openssl rand -hex 32)

CORS_SCHEME="${CORS_SCHEME:-http}"
case "$CORS_SCHEME" in
  http | https) ;;
  *)
    msg_error "Invalid CORS_SCHEME '${CORS_SCHEME}' (expected 'http' or 'https')"
    exit 1
    ;;
esac

ALLOW_INSECURE_CORS="${ALLOW_INSECURE_CORS:-false}"
case "$ALLOW_INSECURE_CORS" in
  true | false) ;;
  *)
    msg_error "Invalid ALLOW_INSECURE_CORS '${ALLOW_INSECURE_CORS}' (expected 'true' or 'false')"
    exit 1
    ;;
esac

cat <<EOF >/opt/rackula/data/.env
RACKULA_API_WRITE_TOKEN=${API_WRITE_TOKEN}
CORS_ORIGIN=${CORS_SCHEME}://localhost
ALLOW_INSECURE_CORS=${ALLOW_INSECURE_CORS}
EOF
chown rackula:rackula /opt/rackula/data/.env
chmod 600 /opt/rackula/data/.env

cat <<EOF >/etc/nginx/snippets/rackula-api-token.conf
# Auto-generated by rackula-install.sh, do not edit manually
set \$rackula_api_write_token "${API_WRITE_TOKEN}";
set \$rackula_has_api_write_token 1;
EOF
chown root:www-data /etc/nginx/snippets/rackula-api-token.conf
chmod 640 /etc/nginx/snippets/rackula-api-token.conf
msg_ok "Generated API write token"

msg_info "Configuring nginx"

cp /opt/rackula/config/nginx.conf /etc/nginx/sites-available/rackula

rm -f /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/rackula /etc/nginx/sites-enabled/rackula
msg_ok "Configured nginx"

msg_info "Creating Services"
cp /opt/rackula/config/rackula-api.service /etc/systemd/system/rackula-api.service

mkdir -p /etc/systemd/system/nginx.service.d
cp /opt/rackula/config/nginx.service.d-override.conf /etc/systemd/system/nginx.service.d/override.conf

systemctl enable -q --now nginx rackula-api
msg_ok "Created Services"

msg_info "Verifying Services"
for i in $(seq 0 9); do
  if curl -sf --connect-timeout 2 --max-time 5 http://127.0.0.1:3001/health >/dev/null 2>&1; then
    msg_ok "Service running successfully"
    break
  fi
  sleep 1
  if [ "$i" -eq 9 ]; then
    msg_error "API failed to start within 10 seconds"
    exit 1
  fi
done

motd_ssh
customize
cleanup_lxc
